### ISSUE TITLE
Add permissions for comment / explain

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#10]
### Comment:

- Allowed (all)
- Not allowed (none)
- ??? based on permissions condition?

### Explain: 

- Allowed (all)
- Not allowed (none)
- ??? Forced – always has to be provided
- ??? based on condition?

@benhaynes

**Comment by benhaynes** [comment]
Yes, this is exactly right. Would we include this under normal permissions? 

If we go that route, it would be good to have a global fallback per role.

If we don't, then I feel like it's easier to set up... but the comment/explained permissions will end up just being set per collection anyway.

Basically it's just two different ways of doing the same thing.

Btw, "permissions" and "force" would be the same thing for _explain_. You're basically choosing when someone _needs_ to explain, otherwise it's basically just a comment, and we can use those permissions.
