### ISSUE TITLE
Pagination control dissapears after navigating to the last page

### ISSUE THREAD

**Issue by dmitrijsc** [directus/next#167]
Hello

Pagination disappears after navigating to the last page. After I scroll to page 984, the control disappears, and I need to navigate the collections menu again. This is a standard listing without filters.

![image](https://user-images.githubusercontent.com/11473040/91219947-2099a300-e724-11ea-994d-39c537c46706.png)

**Comment by rijkvanzanten** [comment]
I'm assuming it's a 0-indexing issue. Could you confirm if page `984` works as expected @dmitrijsc?

**Comment by rijkvanzanten** [comment]
Oh wait, if pagination disappears, it's a hell of a job to get to 983 of course 😂

**Comment by dmitrijsc** [comment]
Tested with a smaller collection, I can see the last page as long as there are dots "..."

![image](https://user-images.githubusercontent.com/11473040/91223646-9f450f00-e729-11ea-8320-7b1f59642094.png)

![image](https://user-images.githubusercontent.com/11473040/91223683-ad932b00-e729-11ea-86c6-b90894628ef9.png)

but once I navigated to page 19 I can also see 20 again

![image](https://user-images.githubusercontent.com/11473040/91223741-c3085500-e729-11ea-9b1f-16529f2c7d3e.png)

**Comment by rijkvanzanten** [comment]
@benhaynes any thoughts? IIRC, you setup the dots-to-numbers setup right?

**Comment by benhaynes** [comment]
Welp, i did fix a different issue in the `v-pagination` component, but this specific one doesn't seem to be part of pagination. Pagination sends the page to the layout, but the layout seems to have an issue... here's what I've found happens:

* Happens on tabular and cards layouts
* `itemCount` gets messed up too (eg: goes from `360` to `23`) when going to the last page
* `page` is set properly (in my case it shows page being `16`... which is right)
* `totalPages` goes back to `1` (instead of `16` in my case)

Back to you, @rijkvanzanten !! 🎾

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-09-18 at 16 25 43](https://user-images.githubusercontent.com/9141017/93642175-9fa09500-f9cb-11ea-82c1-b4110ecf01ad.png)

![CleanShot 2020-09-18 at 16 25 56](https://user-images.githubusercontent.com/9141017/93642183-a3ccb280-f9cb-11ea-87b5-4dc38c949b75.png)
