### ISSUE TITLE
Storage of Date/Time in DB

### ISSUE THREAD

**Issue by Nitwel** [directus/next#207]
## The Problem: How should Date/Time values be stored.

The current API(MariaDB) stores a Date as `2020-09-04` but the API returns `2020-09-03T22:00:00.000Z`,
which is relative to the API's timezone. (for me +2)

This would cause users of other timezones to see the date as `September 3rd 2020` where I would see the date as `September 4th 2020` because I'm in the same timezone.

#### Way 1: Make it relative to the Api location
This is how it is currently implemented:
When a user living in NY sets the date to `{"date":"2020-09-04T00:00:00-06:00"}` (example body), the Api will take the date values and completely igonres the timezone. (Saves `2020-09-04`). When the api now is in a (+2) timezone, it will send the date back as `2020-09-03T22:00:00.000Z`. When the NY user now want's to see this value, he would see `2020-09-03` as the date converted to NY timezone would be `2020-09-03 16:00:00`.

#### Way 2: Make it relative to the user who set it
When a user saves a date, the api calculates it's own timezone relative to the users location.
So when user1, who set the date in his timezone (+3) to `2020-08-12` and tells another user living in (+2) to look at the date, the second user would see `2020-08-11` as the date. Only users living at +3 or higher would see the date as user1 had set it.

### Solution 2: Make it global
When user1 sets the date to `2020-08-12`, everybody else on the world would see the exact same date as user1.

----
Both solutions are also applicable for times!

----

### My personal opinion
I would choose the 2nd solution because the first ones could in theory cause confusion about the dates not being the same across countries and so on.

**Comment by rijkvanzanten** [comment]
> This is how it is currently implemented:
> When a user living in NY sets the date to {"date":"2020-09-04T00:00:00-06:00"} (example body), the Api will take the date values and completely igonres the timezone. (Saves 2020-09-04). When the api now is in a (+2) timezone, it will send the date back as 2020-09-03T22:00:00.000Z. When the NY user now want's to see this value, he would see 2020-09-03 as the date converted to NY timezone would be 2020-09-03 16:00:00.

@Nitwel This sounds MySQL specific. Have you checked how this works in Postgres with the `timestampz` type?

**Comment by Nitwel** [comment]
![grafik](https://user-images.githubusercontent.com/22577866/92284750-03728a80-ef03-11ea-8152-a7d29228ac7e.png)
As far as I can see here Postgres would save date values the same way as MySQL but I have not tested this yet!

**Comment by rijkvanzanten** [comment]
My 2¢:

`date` should save/retrieve as `YYYY-MM-DD`, no timezone
`time` should save/retrieve as `HH-MM-SS`, no timezone
`datetime` should save/retrieve as ISO8601 _without_ timezone
`timestamp` should save/retrieve as ISO8601 _with_ timezone

I think the differentiation between `datetime` and `timestamp` is crucial here.

For example: if @Nitwel adds an item to the calendar saying he's available from `09:00` to `17:00`, it should be saved in his local timezone (+2). That way, when I look a the data in the calendar layout, my calendar will show @Nitwel's availability as 3am–11am, which allows me to correctly plan my day.

In the same vein, activities that are "all day" (and therefore the `date` type), should _not_ adhere to any sort of timezone offsets, cause that causes the "9/3 instead of 9/4" issue (where it offsets 00:00:00 with the local timezone (-6))

**Comment by rijkvanzanten** [comment]
@Nitwel The second row `timestamp with timezone` is crucial. MySQL auto-converts any timezone info to UTC when using `timestamp`, while Postgres stores the actual timezone used

**Comment by WoLfulus** [comment]
I'd personally store (convert if needed) it all in UTC (no matter the backend), because some databases doesn't support TZ as PG does. Then the timezone shift gets calculated based on the user logged user/browser detected timezone and/or if specified in the API to convert to another timezone. Otherwise always returns as UTC.

But for this to work we should either enforce passing a date format with TZ, or explicitly says that if one isn't set it's going to get converted to UTC based on the server's configured timezone.

**Comment by Nitwel** [comment]
@rijkvanzanten could you give me an direct example how postgres would store a date? I'm still trying to get postgres to work...

**Comment by rijkvanzanten** [comment]
**Input**:

`2020-09-04T17:27:57-06`

**Saves**:


| MySQL | `2020-09-04 21:27:57` |
| --- | --- |
| Postgres | `2020-09-04T17:27:57-06` |

**Is currently returned as**

| MySQL | `2020-09-04T21:27:57Z` |
| --- | --- |
| Postgres | `2020-09-04T17:27:57-06` |

**Comment by Nitwel** [comment]
I'm speaking about date or time not date-time. 😄

**Comment by everyx** [comment]
> I'd personally store (convert if needed) it all in UTC (no matter the backend), because some databases doesn't support TZ as PG does. Then when returning those values, the timezone shift gets calculated based on the user logged user/browser detected timezone and/or if specified in the API to convert to another timezone. Otherwise always returns as UTC.

@WoLfulus +1 Super agree 

> But for this to work we should either enforce passing a date format with TZ, or explicitly says that if one isn't set it's going to get converted to UTC based on the server's configured timezone.
> 

We should also consider use the timezone of user's profile timezone setting first, if is none, will fallback to server's configuration.


> Edit: a lot of answers while I was writing :P

**Comment by benhaynes** [comment]
This has been an issue for almost a decade, so I'm glad that we are going to resolve it once and for all before version 9.0 is even released. I think the most important things here are: consistency, reliability, flexibility, and intuitiveness. 

Because database vendors might save these values in slightly different ways, we need a way to be consistent across all of them. I think what Rijk said is the only one that checks off most of those boxes given these differences...

* `date` should save/retrieve as YYYY-MM-DD, no timezone
* `time` should save/retrieve as HH-MM-SS, no timezone
* `datetime` should save/retrieve as ISO8601 without timezone
* `timestamp` should save/retrieve as ISO8601 with timezone

By going this route, values returned are consistent across database vendors and regardless of server or user location. At this point it simply becomes a docs issue, if you want to save a value in a specific way, you use a specific data type... and we have one for every permutation.

The problem with converting a datetime to a specific time zone automatically (either unsaved, or when being returned) is that that might not be the intention of the admin/user. For global brands with content authors around the world, all scheduling classes for a specific studio... you need to ensure the integrity of the date and time saved in a way that it won't change based on time zone (`datetime` in Rijk's example). However if you want the automation of a dynamic time zone, you could use the `timestamp` data type.

The only annoyance with this approach is that certain database types might be handled differently across vendors. But in my view, we need to standardize that to avoid confusion, and make this a docs issue.

**Comment by everyx** [comment]
> My 2¢:
> 
> `date` should save/retrieve as `YYYY-MM-DD`, no timezone
> `time` should save/retrieve as `HH-MM-SS`, no timezone
> `datetime` should save/retrieve as ISO8601 _without_ timezone
> `timestamp` should save/retrieve as ISO8601 _with_ timezone
> 
> I think the differentiation between `datetime` and `timestamp` is crucial here.
> 
> For example: if @Nitwel adds an item to the calendar saying he's available from `09:00` to `17:00`, it should be saved in his local timezone (+2). That way, when I look a the data in the calendar layout, my calendar will show @Nitwel's availability as 3am–11am, which allows me to correctly plan my day.
> 
> In the same vein, activities that are "all day" (and therefore the `date` type), should _not_ adhere to any sort of timezone offsets, cause that causes the "9/3 instead of 9/4" issue (where it offsets 00:00:00 with the local timezone (-6))

@rijkvanzanten In my opinion, in datetime interface, we should have a option to let us enable timezone support feature something like as timestamp interface.

**Comment by rijkvanzanten** [comment]
@everyx i agree. When the timestamp type is used the datetime interface should have an additional field for time zone, that defaults to your local time
