### ISSUE TITLE
More detailed relational setup

### ISSUE THREAD

**Issue by Nitwel** [directus/next#224]
It would be helpful to have a detailed information on what each dropdown does / what you have to to to setup a relation.

![grafik](https://user-images.githubusercontent.com/22577866/92616287-54e19780-f2be-11ea-85c5-290495c25c52.png)

**Comment by rijkvanzanten** [comment]
@benhaynes Any thoughts on this? Sounds like a docs problem to me, seeing there isn't much more we can do to actually simplify this schema I don't think 🤔 

Having a "learn more" link somewhere on this pane is probably the most helpful solution

**Comment by benhaynes** [comment]
Yeah, I'd like to avoid having docs baked in too much... since that's just in the way once you know what you're doing. But I think a link to **versioned** docs would help. Or small hints, such as tooltips on an "Info" icon:

![Screen Shot 2020-09-09 at 11 47 31 AM](https://user-images.githubusercontent.com/522079/92621783-44b3c300-f292-11ea-9ae2-164c1367125e.png)

**Comment by rijkvanzanten** [comment]
I believe the updated flow is much clearer than what it was before, we can revisit if needed
