### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#330]
There seems to be a combination of variables that sits a little funny in pagination. 

In this case, `totalVisible == 7` + `length == 6` results in:

![CleanShot 2020-09-18 at 16 34 26](https://user-images.githubusercontent.com/9141017/93642865-d32fef00-f9cc-11ea-9664-41aa5636dec6.png)

![CleanShot 2020-09-18 at 16 34 33](https://user-images.githubusercontent.com/9141017/93642873-d6c37600-f9cc-11ea-9bb5-ff6a76fe9917.png)

(3 & 4 are correct)

![CleanShot 2020-09-18 at 16 34 54](https://user-images.githubusercontent.com/9141017/93642906-e478fb80-f9cc-11ea-8966-11bae9285762.png)

![CleanShot 2020-09-18 at 16 35 02](https://user-images.githubusercontent.com/9141017/93642914-e93daf80-f9cc-11ea-8d9a-8ce95a8655c6.png)

**Comment by benhaynes** [comment]
This should be resolved now. I tested many permutations and they were all correct.

The only annoyance is that if you have "Show First/Last" enabled, the "TotalVisible" is technically two higher... since it just adds those additional buttons. Also, this combined with the "..." buttons, and variable width buttons means that things jump around a bit under your cursor when clicking quickly. I don't think this is a huge issue for now though, since clicking a page typically scrolls to you up the the top of the page/context.
