### ISSUE TITLE
Reset Password: Go back

### ISSUE THREAD

**Issue by shealavington** [directus/next#37]
The words "Sign in" confused me as for a moment, I didn't really realize it was a button to go back to the sign-in page, maybe "Go back"?

Suggestion, feel free to close if you disagree :P 

![image](https://user-images.githubusercontent.com/16869302/89403387-1df0f280-d710-11ea-9cb4-4b0147752ef6.png)

**Comment by rijkvanzanten** [comment]
@benhaynes thoughts on the messaging here?

**Comment by benhaynes** [comment]
I don't think "Go Back" works since it's unclear where _back_ is, and technically you could come to this page directly... So there is no back.

I think this language is pretty standard, but we could clarify it as "Back to Sign In". Just worried about it being overly verbose. Maybe we can look around to see how others label it.

**Comment by shealavington** [comment]
Just looking through issues, could we use like, a long arrow icon to indicate an action? «--

**Comment by rijkvanzanten** [comment]
@shealavington Little worried that it then feels like the arrow is pointing to the button 

![CleanShot 2020-09-18 at 17 12 44](https://user-images.githubusercontent.com/9141017/93645517-2f494200-f9d2-11ea-85d7-8dd3e73505bf.png)

**Comment by benhaynes** [comment]
It's a valid point, but I'll close this for now and we'll see if anyone else find this flow/language confusing. I'm down to change it... but this will all change a bit once "Register" is also included.
