### ISSUE TITLE
Add back "Hidden on Browse"

### ISSUE THREAD

**Issue by benhaynes** [directus/next#391]
## Defaults
* Normal Fields: Show on Detail + Show on Browse
* Dividers: Show on Detail + **Hide** on Browse
* User Created: **Hide** on Detail + Show on Browse
* Hidden Fields: **Hide** on Detail + **Hide** on Browse

**Comment by maartenvn** [comment]
Why is this closed? I don't see any option to hide a field on browse?

**Comment by maartenvn** [comment]
Right now there is a single field (`hidden`) that determines whether a field is hidden on the detail page or not. There is no way to disable an item on the browse page.

## Suggestion
Split the `hidden` field into 2 separate fields:
- `hidden_browse`
- `hidden_detail`

Since Directus is showing "hidden" fields in grey, I would suggest only greying a field out when it is both  `hidden_browse` & `hidden_detail`:
![image](https://user-images.githubusercontent.com/6013068/96335820-8a2a9380-107b-11eb-9559-186b19dcc267.png)

**Comment by benhaynes** [comment]
We decided to go a slightly different route with this .

Hidden still only controls the form, and all _data_ fields are available on browse. The issue I wanted to solve for was not showing **non-data** fields like dividers, groups, and other aliases on the browse pages... which this change does based on a special flag.

Since the browse page can have any layout, it's very difficult to know how a "hidden on browse" would work (eg: does it override a card layout's template?), and having two different hidden toggles makes things unnecessarily confusing.

I prefer this approach, but if you disagree, feel free to open a discussion about it!

**Comment by maartenvn** [comment]
I didn't know presets could replace the default layout, so makes sence to not implement it the way I described.

---

For future reference to anyone searching for this issue coming from v8:

You can still configure which fields will be showed on the collection browse page using **presets**:

1. Go to Settings -> Presets
2. Create a new preset
3. Choose the collection & **leave the name empty**
4. Go to Layout Options in the sidebar & choose which fields to display

This will replace the existing view for the collection
