### ISSUE TITLE
Changing Primary Key: Breaks Interface

### ISSUE THREAD

**Issue by shealavington** [directus/next#439]
If I have my PK setup to be a string
I create an item with id of ALPHA
I open the item and change the ID to BRAVO
the page is still on '/alpha' therefore it should redirect to new item if I do save and stay
The page also breaks and logs me out if I navigate away from the now uncreated page ('/alpha').

**Comment by benhaynes** [comment]
This one is interesting, since we've never actually allowed changing primary keys in the past. The reason being, the primary key is used to relationally store all references to the item... Including in activity, revisions, etc. 

I like the idea of being able to change the PK, but we probably would need to look into updating all relational records if we do, or at least the system ones, and throwing an warning that all other relationships may be broken.

**Comment by rijkvanzanten** [comment]
We'll have to "hard-lock" the pk field on update for this exact reason.
