### ISSUE TITLE
Notify devs about .env on project setup

### ISSUE THREAD

**Issue by shealavington** [directus/next#44]
When someone has installed Directus for the first time or started the server, the developer could be notified of the .env file incase they need to make any immediate changes, this avoids the need for documentation search for a quick FYI notice.

**Comment by WoLfulus** [comment]
Laravel generates a .env based on a .env.example file when root package is installed (and .env cannot be found). Maybe something like this can be done too? It's pretty handy and since there are values there already, doesn't need to go through documentation to find them.

**Comment by rijkvanzanten** [comment]
[I'm using a stub](https://github.com/directus/next/blob/main/api/src/cli/utils/create-env/env-stub.liquid) that's being injected with the generated / configured values, so that's very similar.

I believe @shealavington means that we should add a little note when the installer is done saying something like 

```
✨ Successfully installed your project.

⚙️ The configuration can be found in /path/to/.env
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

🔍 Run `npx directus start` to start the project
```

**Comment by WoLfulus** [comment]
oh that makes sense
