### ISSUE TITLE
Add /graphql endpoint

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/next#5]

**Comment by WoLfulus** [comment]
On PHP, we have two:

- `/data` for data-related queries & mutations
- `/system` for system related queries & mutations

Mixing both in the same schema showed to be a real pain to manage because of name clashes and schema generation gets tricky too.

For reference, this is where we store the non-generated part of the schema:

https://github.com/directus/api-next/tree/master/graphql

You'll be able to generate/view the generated schema (with user tables) from command line too (useful for inspection and analysis)

**Comment by guilhermeaiolfi** [comment]
Those ```.graphql``` files should be shared between node.js and PHP, don't you think? Congrats to @WoLfulus. This graphql endpoint in PHP is incredible. That part for loading/building the types/directives/resolvers/etc and how it connects everything 
 together could be a library by itself 👏

**Comment by WoLfulus** [comment]
It is actually! Most of it I extracted from Lighthouse! I asked the maintainer of lighthouse if we could extract it as a library but we havent interacted since I "stopped" working on the laravel port

**Comment by benhaynes** [comment]
"Paused" working. 😉

**Comment by WoLfulus** [comment]
Exactly! :P
