### ISSUE TITLE
Field layout options

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#709]
In v8 we had options like half-right and half-left which seems to be supported but hidden in the menu's code. Anyway, for more flexible options, what about including some like 'quarter' and 'third'?

**Comment by Nitwel** [comment]
You can customize the width of a field in the data-model section of the settings.
There is no way to force a field to the right only, you always need to have a half width field on the left for that to work.
![grafik](https://user-images.githubusercontent.com/22577866/96419715-cf260580-11f4-11eb-9807-1a9304033da1.png)

I don't think there will ever be a plan to support other widths because this would be a breaking change.

**Comment by rijkvanzanten** [comment]
To clarify, we don't have thirds or even quarters as there are barely any interfaces that would potentially work properly at that size. 

(@Nitwel FYI adding support for this is not considered a breaking change)

**Comment by Nitwel** [comment]
Then I should have clarified that it is meant as a breaking change layout wise. Or as you said, we do not support these layout formats.
