### ISSUE TITLE
[MSSQL] Does not work on v9.0.0-rc0

### ISSUE THREAD

**Issue by mscbpi** [directus/next#711]
MSSQL DB does not at all.

```
08:27:12 🚨 RequestError select top (@p0) [directus_roles].[id], [directus_roles].[name], [directus_roles].[icon], [directus_roles].[description], [directus_roles].[ip_access], [directus_roles].[enforce_tfa], [directus_roles].[module_list], [directus_roles].[collection_list], [directus_roles].[admin_access], [directus_roles].[app_access] from [directus_roles] where [directus_roles].[id] in ((@p1, @p2)) - Incorrect syntax near ','.
```
Seems duplicate to https://github.com/directus/next/issues/409 but we're now in RC and we can't even login MSSQL.

**Comment by benhaynes** [comment]
Seems to be the exact same, so I'll close this as a duplicate. Yes, we're aware this is an RC and there are 2 database vendors still not working (MS-SQL and OracleDB)... that's why we added the "alpha" notice next to them in the CLI installer. We'll be getting these fixed soon, but in the meantime wanted to keep things moving forward for Postgres, MySQL, and SQLite.

**Comment by mscbpi** [comment]
Thanks for the clarification !
