### ISSUE TITLE
Permissions/me route

### ISSUE THREAD

**Issue by Nitwel** [directus/next#81]
Should the `perms/me` and `perms/me/{collection}` route be implemented?

**Comment by rijkvanzanten** [comment]
Sounds useful to me! Also a good way to ensure that regular users always have "access" to the permissions they need to have in order to know what access they have. This would mean we can use "regular permissions" for the /permissions endpoint (eg making sure users can't read anything, or read a specific set) while the app is still able to work properly

**Comment by rijkvanzanten** [comment]
Also @Nitwel, try to use Discussions for feature requests 😄 Works surprisingly well! https://github.com/directus/next/discussions/category_choices
