### ISSUE TITLE
Divider doesn't get translated

### ISSUE THREAD

**Issue by Fusseldieb** [directus/next#957]
Just noticed that even if I include a translation for the divider, it gets ignored. On other fields it works just fine. This bug is present in both v8.8.1 and v9.0.0-rc10.

![image](https://user-images.githubusercontent.com/4715129/98860675-cebf0a00-2442-11eb-8a57-291922bde052.png)

---

![image](https://user-images.githubusercontent.com/4715129/98860717-dd0d2600-2442-11eb-96c6-026b80424a97.png)

Results in:
![image](https://user-images.githubusercontent.com/4715129/98860758-e8f8e800-2442-11eb-8981-ed098ba8c8e9.png)

Language is set to German in this example and almost all the fields get translated as they should, but the divider unfortunately wont.

**Comment by rijkvanzanten** [comment]
That's because that text "Weights" is set in the interface option `Title`, and isn't actually the field name. 

There's a feature request to allow users to plugin their own translations that can be used in "other" places like interface options, see https://github.com/directus/next/discussions/337 for more on that 🙂

**Comment by Fusseldieb** [comment]
> That's because that text "Weights" is set in the interface option `Title`, and isn't actually the field name.
> 
> There's a feature request to allow users to plugin their own translations that can be used in "other" places like interface options, see #337 for more on that 🙂

A really cool solution to this problem! Anxiously looking forward to this 🚀
